// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID        uuid.UUID
	Name      string
	Url       string
	UserID    uuid.UUID
	Createdat time.Time
	Updatedat time.Time
}

type FeedFollow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	Createdat time.Time
	Updatedat time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Createdat time.Time
	Updatedat time.Time
	Apikey    string
}
